### ISSUE TITLE
if /dropbox/job_id directory doesn't exist in images app, the publish fails

### ISSUE THREAD

**Issue by jenlindner** [nulib/menu#37]
i'm getting around it by passing the path to menu's directory, where the base db setup ensures those folders will be there. but this needs to be addressed, not exactly sure if that's menu's or images' job.

**Comment by csyversen** [comment]
i think this is intended. in production images and menu are both going to be pointing to the exact same shared directory, so there shouldn't be a way that a directory would exist in one app and not in another.
